### ISSUE TITLE
general: add the follow list of initiatives

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#10]
- [x] http://www.chicaspoderosas.org/
- [x] http://marialab.com.br/
- [x] http://minasprogramam.com/

**Comment by harsh183** [comment]
I think marialab is gone, so point adding it, looks it was last active in 2015.

**Comment by hi-hi-ray** [comment]
Maria Lab Changed the address. https://marialab.org

**Comment by harsh183** [comment]
The posts seem to date from 2015, are they still active?

**Comment by hi-hi-ray** [comment]
Yes, they are! Mostly participating and doing events. =]

**Comment by harsh183** [comment]
Oh alright, would you like to do it? I can't due to the language barrier.

**Comment by hi-hi-ray** [comment]
Sure!

**Comment by hi-hi-ray** [comment]
Hey Guys! 
I was trying to find a category to place MariaLab, but i don't know which group i can fit them...

Maria Lab actually is a Feminist Hacker Space. The members it's always going to meetups and events to talk about something and sometimes they do some workshops... The most recurrent event it's "Coffee with Maria Lab".

Where I can put then?

**Comment by ztmeyer** [comment]
Hey all - I took a crack at adding the Minas Program in this PR: https://github.com/cristianoliveira/awesome4girls/pull/80

Happy to make any further changes

**Comment by harsh183** [comment]
@hi-hi-ray I think you can go ahead with Maria Lab, I'll review the final description.

@ztmeyer Thanks for minas program, @hi-hi-ray you don't need to do it, if you have something to add on feel free to do so
