### ISSUE TITLE
conference: add Watermark Conference for Women

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#108]
Add https://www.watermarkconferenceforwomen.org/conference/

**Comment by cristianoliveira** [comment]
Related to #6

**Comment by eshton-martin** [comment]
#118

**Comment by cristianoliveira** [comment]
😄

**Comment by harsh183** [comment]
Tbh I had kind of forgotten about this, but I got a notification in my email and decided to clean up a little.
