### ISSUE TITLE
tests: Add specs to enforce project format

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#110]
Today we have some specs made on #106 that enforce:
- List order
- Unique links
- Avoid broken links

We would like to enforce the follow format for each project on the list that is:
 - (name)+(link)
(return)
(description)
(return)

I am not totally sure how to achieve this but would be really nice to have :)

**Comment by harsh183** [comment]
@cristianoliveira I think I'll try this for next week. Does that work?

**Comment by cristianoliveira** [comment]
Sure. Go for it

**Comment by harsh183** [comment]
@cristianoliveira How do I run it?

**Comment by harsh183** [comment]
Will I be able to just download on my local and run it?

**Comment by cristianoliveira** [comment]
> @cristianoliveira How do I run it?
Using `rake` or `rspec` commands

>Will I be able to just download on my local and run it?
I hope yes. For testing you will need:
  - Ruby 2.4.2
  - Bundle (gem install bundle)

Then you can run:
```
bundle install
rspec
```

**Comment by harsh183** [comment]
Sure, glad to know I don't need anything fancy.
