### ISSUE TITLE
Bug: Make alphabetical order spec be case insensitive.

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#120]
Let's take the example of this: https://travis-ci.org/cristianoliveira/awesome4girls/builds/294426635?utm_source=github_status&utm_medium=notification

The spec is failing because while it's correct based on ASCII based order, most humans would sort it case insensitively. I think having it case insensitive would be better.

**Comment by cristianoliveira** [comment]
Good catch!

**Comment by harsh183** [comment]
Sure, I'll hold on working on any specs until the contribution guide is complete.

I'm also thinking, since the file will now follow stricter standards why don't we move onto a .yml that stores all the info and a bot autogenerates the file. People can just add an entry to the yml file and we'll not have to worry too much.  

Is that too overengineered though? Maybe for a later stage, in any case, the specs work fine.
