### ISSUE TITLE
javascript: Add http://webschool.io/js4girls/

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#137]
Recently I removed the Js4girl project cause their site was not available. Turned out they changed to http://webschool.io/js4girls/

Please add them under javascript section

**Comment by harsh183** [comment]
Can you give the old description?

**Comment by cristianoliveira** [comment]
Sure here it is:
```
Js4Girls - Loc: Brazil - Lang: PT-BR only

A Brazilian initiative to provide FREE classes on javascript to women in a male-free environment.
```

**Comment by harsh183** [comment]
Sure, it's late here, but I'll get to this one tomorrow (and the specs).

**Comment by cristianoliveira** [comment]
No worrie man :)

I opened those issues just to not forget. We can add as soon we have some time 🍻

**Comment by harsh183** [comment]
I'll trust that description is correct, I don't understand Portuguese, but judging by common words between Spanish the description looks okay.

**Comment by cristianoliveira** [comment]
> I'll trust that description is correct, I don't understand Portuguese, but judging by common words between Spanish the description looks okay.

If you know Spanish you basically know Portuguese hehehe (not exactly but it's true most of the time) 😆

**Comment by harsh183** [comment]
@cristianoliveira Well I've been learning Spanish for a very short time, but I could see a few phrases here and there and many common words
