### ISSUE TITLE
Suggestion: Add ticket prices on events

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#142]
I think having ticket prices/and other restrictions there in the page. It would help people who are interested and may not be able to afford everything, and checking each can get quite cumbersome, I have a few on file, but we can create issues for each of them.

**Comment by harsh183** [comment]
@cristianoliveira

**Comment by cristianoliveira** [comment]
I am not sure. The problem is that we will need to check if the prices are the same constantly to keep consistency

**Comment by harsh183** [comment]
True, it becomes a practicality issue. It can be useful, but it's enormous effort on our ends.
