### ISSUE TITLE
Fix: change js4girs link to https://github.com/Webschool-io/js4girls

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#144]
Running the tests recently I noticed that the website of js4girls isn't up anymore(again). I searched for a more stable alternative and ran into their github repo. So it could be the link for this project.

**Comment by cristianoliveira** [comment]
I am already working on it :)

**Comment by harsh183** [comment]
I'm debating if it's worth having a checker making sure that each link works. What do you think?

**Comment by cristianoliveira** [comment]
Well, I think it is important because some of then may be broken. In my opinion, a list that provides broken links lose credibility same as any other site :)
