### ISSUE TITLE
Please Add ACT-W National Conference (Advancing the Careers of Technical Women) 

### ISSUE THREAD

**Issue by britneymorgan** [cristianoliveira/awesome4girls#148]
ACT-W National [](http://www.act-w.org/)

Presented by ChickTech, ACT-W National focuses on providing you with inspiring and actionable education in career development, leadership, technology, and diversity.

ACT-W National is an engaging 3-day conference where talented women and supporters in tech can accelerate their career by connecting with organizations and leaders in the community. The conference includes speaking sessions, “training the trainer” workshops, one-on-one coaching sessions, a Career/Exhibit Fair, after hours parties, networking, and more!

**Comment by cristianoliveira** [comment]
Hey @britneymorgan 

Thanks for letting us know :)
We will take a look at it and add it.

**Comment by rkraeher** [comment]
ya sure thing
