### ISSUE TITLE
search: Initiatives in the Oracle community.

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#20]
Search for initiatives from Oracle.

**Comment by harsh183** [comment]
I found a couple, let me know which ones should we add by creating a new essay for each entry. 

1. http://www.oracle.com/technetwork/community/women-in-tech/overview/index.html
2. http://www.oracle.com/us/corporate/citizenship/introduction/women-leadership-1886282.html

Not Oracle, but
1. https://www.pwc.com/us/en/about-us/diversity/women-technology.html

**Comment by harsh183** [comment]
Shall we close this?
