### ISSUE TITLE
Stop adding famous developers to this repo collaborators!

### ISSUE THREAD

**Issue by KubaKaszycki** [cristianoliveira/awesome4girls#24]
I have seen such pop-up on main page:
![zrzut ekranu 2016-02-24 o 20 21 15](https://cloud.githubusercontent.com/assets/15962707/13297773/4680752c-db34-11e5-93f0-b7db503d5040.png)
Linus Torvalds is a **male**, I think he's not interested in this repo. Please, don't do bad **DOUBLE**!

**Comment by cristianoliveira** [comment]
Sorry, was a typo. I've already fixed. I've sent a email to github to fix it.

**Comment by andviera** [comment]
It is a gap on github I think. You can add anyone then this things happens.
