### ISSUE TITLE
general: add mothership.hackermoms

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#27]
- Create description.

**Comment by harsh183** [comment]
The description from Wikipedia could serve as a starting point: 

Mothership HackerMoms is a nonprofit hackerspace/makerspace in Berkeley, California, founded in 2011. It was the first all-women hackerspace.

The 1000-square-foot space provides space for members to work on projects and hold events while their children are onsite with child care. They have participated in DIY culture events such as Maker Faire, Bizarre Bazaar, and Oakland Art Murmur, and have access to another San Francisco Bay Area hackerspace, Ace Monster Toys. The members define Mothership HackerMoms as a hackerspace deliberately to include themselves in the open source and free culture movements. Members have held workshops on how to use Drupal and Illustrator, how to lay a resin coating on a canvas, done painting, drawing, photography, and made linoprints.

**Comment by hi-hi-ray** [comment]
I can Do it =]

**Comment by harsh183** [comment]
@hi-hi-ray Great! Let me and @cristianoliveira  know when you submit a PR.

**Comment by hi-hi-ray** [comment]
It's open guys (@harsh183  and @cristianoliveira)! 

Pull Request: #85

**Comment by harsh183** [comment]
Looks great! I like your contributions on this repo quite a bit.
