### ISSUE TITLE
general: add rodadahacker.org

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#28]
- Create a description

**Comment by hi-hi-ray** [comment]
Hi, Can I be assignee to this issue?

**Comment by cristianoliveira** [comment]
Hey @hi-hi-ray feel free to start it :)

I am not able to actually sign it to you, cause only "Collaborators" can be assigned to issues :(

**Comment by hi-hi-ray** [comment]
That's OK!  😺 

I'm new in this format of project and i have some questions. 

I was exploring the repository,  and realized that has 2 files containing the list of events/projects/initiatives, Can i add the description and Link on the following files:
- Readme.md
- fixtures/Readme.md

If there any other file that i must change, do you mind tell me?

**Comment by harsh183** [comment]
Just edit the README.md file. The others you can leave for now. The process is pretty simple, just write a description, add it to the file and make a pull request. 

@cristianoliveira Should we rewrite the contribution guide?

**Comment by hi-hi-ray** [comment]
The contribution guide it's correct, it's just me who is doing a contribution for the first time. :D

**Comment by harsh183** [comment]
Haha alright, I was quite confused when I first came here too. Looking forward to seeing you become a regular though.

**Comment by cristianoliveira** [comment]
> @cristianoliveira Should we rewrite the contribution guide?

Would be really nice! 
I thought I had already done for this project? 🤔 
So maybe I made it for another 😅

**Comment by cristianoliveira** [comment]
No its there. https://github.com/cristianoliveira/awesome4girls/blob/master/CONTRIBUTING.md

Maybe we can improove with some explanation steps by step.

@hi-hi-ray don't worry we all be confuse in our firsts PR. We are here to help :)

**Comment by harsh183** [comment]
I just read it, it's not very clear. I think I'll rewrite it after school tomorrow.

**Comment by cristianoliveira** [comment]
Fixed by #78
