### ISSUE TITLE
feat: site to expose the list

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#33]
Create a simple site to share this data and maybe the events dates.

**Comment by cristianoliveira** [comment]
First step is done: https://github.com/cristianoliveira/awesome4girls-api

**Comment by harsh183** [comment]
Is a site needed? Can we just add the dates onto a google calendar or excel sheet online? I think having a website will be too overkill.

**Comment by cristianoliveira** [comment]
Yeah not sure if it is needed indeed. I was building just for fun 😅

**Comment by harsh183** [comment]
I can relate. It's lying a little stagnant though. Initially I found this repo since it was tagged with Ruby (I'm mainly a Rails guy)
