### ISSUE TITLE
general: add anitas.com.br

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#44]

**Comment by jcserracampos** [comment]
Can I take this?

**Comment by cristianoliveira** [comment]
Hallo @jcserracampos 
Sure, go for it! :)

**Comment by harsh183** [comment]
@jcserracampos Any luck?

**Comment by harsh183** [comment]
I think it probably closed. No point adding it.

**Comment by hi-hi-ray** [comment]
@jcserracampos You can try contact then on their facebook page. =]

https://www.facebook.com/AnitasFloripa/

**Comment by harsh183** [comment]
@hi-hi-ray Great catch! Can you write a description for them?

**Comment by deboraazevedo** [comment]
Hello! I know the girls who currently run Anitas, I think I can help :)

**Comment by cristianoliveira** [comment]
Hey @deboraazevedo Thanks! It will be awesome

**Comment by harsh183** [comment]
@deboraazevedo If you know about people who run any organisations in our list or any others, please add it here. We'd really appreciate it.

**Comment by harsh183** [comment]
Hey guys, any progress?

**Comment by deboraazevedo** [comment]
Hey there! I'll finally got some answer from the organizers and I'll be pushing to the repo this week

**Comment by harsh183** [comment]
@deboraazevedo Sure! Great to hear. Tag me or @cristianoliveira when you submit a PR.

**Comment by harsh183** [comment]
@deboraazevedo Any luck?

**Comment by deboraazevedo** [comment]
@harsh183 @cristianoliveira just submitted the pull request!
