### ISSUE TITLE
general: add Bay area Girls

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#5]
Need a description.
http://bayareagirlgeekdinners.com/about/

**Comment by harsh183** [comment]
Company sponsored dinners in the San Francisco Bay Area which invite women from various areas of technology to share their experiences, alongside prominent speakers from the female tech community, networking and potential recruiting by the sponsoring company. It has been hosted by 100+ companies and has several events per month.

**Comment by harsh183** [comment]
@cristianoliveira Look okay?

**Comment by harsh183** [comment]
https://github.com/cristianoliveira/awesome4girls/pull/68
