### ISSUE TITLE
Ada Camp

### ISSUE THREAD

**Issue by elle** [cristianoliveira/awesome4girls#51]
A  two-day unconference run by the Ada Initiative and dedicated to increasing women’s participation in open technology and culture
https://adacamp.org

**Comment by harsh183** [comment]
Is this an issue?

**Comment by cristianoliveira** [comment]
Hey @harsh183 yeah it is an "issue". Actually, the task here is pretty simple we need to find the best description for `https://adacamp.org` project (@elle has already done this for us) and look at the list to figure out where it fits best. I would say under "Intiatives/Programs" > "Academy/Camp"

Feel free to ask anything regarding the task :)

**Comment by harsh183** [comment]
Sounds great, can I see @elle 's description?

I'd say  "Intiatives/Programs" > "Academy/Camp" looks pretty good.

Need me to do anything?

**Comment by cristianoliveira** [comment]
Hey @harsh183 Basically we need to add this project/event/camp to `Readme` in the correct section. You can take a look at the other to take as an example.

**Comment by harsh183** [comment]
Okay, I did some looking up. I don't think we should add AdaCamp since it's no longer held since 2015, and the organizers are not planning new ones.

They've mostly released their materials which they used for their own unconferences for others to use in form of the AdaCamp toolkit. It's high-quality material, and I think we can add a mention of the Ada Camp under a section like 'Resources for starting your own conferences'

**Comment by cristianoliveira** [comment]
> Okay, I did some looking up. I don't think we should add AdaCamp since it's no longer held since 2015, and the organizers are not planning new ones.

That actually is a good point. 

> They've mostly released their materials which they used for their own unconferences for others to use in form of the AdaCamp toolkit. It's high-quality material, and I think we can add a mention of the Ada Camp under a section like 'Resources for starting your own conferences'

Or maybe under "Other initiatives > Content" ? https://github.com/cristianoliveira/awesome4girls#content

**Comment by harsh183** [comment]
I don't think it will fit well in there. I say we create a new section on the lines of  'Resources for starting your own conferences'.

**Comment by cristianoliveira** [comment]
I think wouldn't be a problem having a new section. Let see if it has more projects to fill in.

**Comment by harsh183** [comment]
Sure, let's look around for a bit, though it's fine if we don't find anything else and the section only has one item.

**Comment by harsh183** [comment]
I can't find any others, shall we add that section with only this?

**Comment by cristianoliveira** [comment]
Then I think we should add it in one of the existent sections

**Comment by harsh183** [comment]
Okay? Which one do you have in mind?

**Comment by cristianoliveira** [comment]
Maybe add on Academy/Camp as you first suggested but add a flag/title or something saying this project isn't happening anymore, something like Deprecated. What you think?

**Comment by harsh183** [comment]
I don't think that'll work. I think having a small section around the bottom with one entry will be fine, and others will add more as time passes.
