### ISSUE TITLE
Minor: Improve League of Women coders description

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#53]
```
League of Women Coders (formerly Ladies Who Code, est. June 2011) is a grassroots collective that focuses on coding, hacking, and learning together. We’re like a book club for superhero women coders. You’ll find us championing free software, debating the best uses for ternary operators, defending against trolls, sharing what we know, and supporting each other in every way we can.
```
Now, this description seems very different from the rest, it directly addresses the audience and uses more emotive language than usual as compared to the rest of the list, maybe rewrite or improve it?

**Comment by harsh183** [comment]
Hmm... I think we should slightly touch up descriptions before putting them up to have more information, and be less emotive.

**Comment by cristianoliveira** [comment]
I agree. Feel free to suggest a new description for that and create a PR with the change :)

**Comment by harsh183** [comment]
League of Women Coders (formerly Ladies Who Code, est. June 2011) is a grassroots collective that focuses on coding, hacking, and learning collaboratively. The group meets up at least once a month in New York City and Boston. 

The meetups involve casual 5-minute lightning talks, asking technical questions, and tossing around ideas. It has a strong networking element, and there is a large emphasis on sharing ideas to improve one's coding skills. Food of the baked variety and pizza is given at the venue. The meetups also bring in interesting lady speakers who talk about various issues in tech and being women in tech.

https://github.com/cristianoliveira/awesome4girls/pull/62
