### ISSUE TITLE
Minor: Improve DigiGirlz Day description

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#54]
```
Microsoft is proud to offer technology programs that target youth. This one-day event, held at multiple Microsoft locations worldwide, is designed to provide high school girls with a better understanding of what a career in technology is all about.
```
I think the first sentence is more marketing and does not really add anything. I think this can be rewritten to maybe mention some of the locations ('Microsoft locations worldwide'), and maybe a little more detail about what the program includes if possible.

**Comment by cristianoliveira** [comment]
Agreed!

**Comment by trouta23** [comment]
Hey there, is this still available to be picked up? If so I'd be happy to work on it.

**Comment by harsh183** [comment]
Go for it
