### ISSUE TITLE
Hacktoberfest: Fix typos

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#56]
Hello, fellow Hacktoberfest contributor!

I am opening this issue, especially for the Hacktoberfest. I am not a native English speaker and I am too used to read the list that I can't see all typos that it may have. 

So I invite you to take a look at the list and if you find out either a typo or a weird sentence please feel free to point it out and open a PR with a fix for it. 😄 

@harsh183 has already started and he got some. many thanks!

Please feel free to ask anything.

**Comment by harsh183** [comment]
I'll probably take a much closer look at the entire listing again, and ask a few friends two. This is something that works better with many people on it. 

So steps for typos (maybe we should write a small guide in the contributing file?)
1. Find typo(s)
2. [Optional if you are fixing it yourself] Create an issue on GitHub
3. Fix typo(s) in your fork of the project
4. Create a commit with the file with the fixed typo(s), make the title start with `Typo:`
5. Create a pull request

**Comment by agonzalez0515** [comment]
Hi! I can help with this if there are any more things to review  :raising_hand_woman:

**Comment by cristianoliveira** [comment]
Hey @agonzalez0515 actually we are not splitting tasks for it feel free to look around and if you notice anything strange open a PR :)

**Comment by harsh183** [comment]
@agonzalez0515 Well, I think you can definitely go over the list and fix some grammar/typos. And go through the other issues as well, if you find anything to work on, go ahead. Report and fix any other issues you find too, as @cristianoliveira said.

**Comment by harsh183** [comment]
@cristianoliveira Should we reopen the same issue under the same name so that other people see it and contribute since this one has many commits and PRs to it.

I think we can also add a small section in the README about reporting typos.

**Comment by cristianoliveira** [comment]
Hey @harsh183 I think would be a good idea. :)

I will close this one. Feel free to open a new one if you think is needed. 👍
