### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/awesome4girls#6]
If you have suggestions wich you would like to see in the list, but you does not want to include it yourself. Please comment here and it will be reviewed and added. :D

**Comment by harsh183** [comment]
1. http://www.pbsnow.com/pinnacle-point/top-7-must-attend-conferences-women-technology-2/
2. https://blog.bizzabo.com/women-in-technology-conferences
3. https://www.themuse.com/advice/4-inspiring-conferences-you-need-to-attend-if-youre-a-woman-in-the-tech-industry
4. https://www.witi.com/conferences/2017/summit/
5. http://www.signority.com/blog/top-5-conferences-2017-for-women-in-tech/

Any of these might work?

**Comment by harsh183** [comment]
@cristianoliveira

**Comment by cristianoliveira** [comment]
Hey @harsh183 that looks great. Some of the projects they listed there we have already added but there are of new also. We could create some issues with them and add the `hacktoberfest` label. WDT?

**Comment by harsh183** [comment]
That sounds good, I'm a little busy this weekend, so can you do it?

**Comment by harsh183** [comment]
I'm just making a checklist:

The task is to go over these lists and identify entries we can add and ensure that they don't already exist.

- [ ] http://www.pbsnow.com/pinnacle-point/top-7-must-attend-conferences-women-technology-2/
- [ ]  https://blog.bizzabo.com/women-in-technology-conferences
- [ ]https://www.themuse.com/advice/4-inspiring-conferences-you-need-to-attend-if-youre-a-woman-in-the-tech-industry
- [ ] https://www.witi.com/conferences/2017/summit/
- [ ] http://www.signority.com/blog/top-5-conferences-2017-for-women-in-tech/

**Comment by harsh183** [comment]
I added a few more issues, I'll finish up adding more issues for the other pages later.

**Comment by harsh183** [comment]
@cristianoliveira  Can you add issues for the entries on [This blog](https://blog.bizzabo.com/women-in-technology-conferences)

There are quite a few, and since we'll have the most number of contributors in the closing days of hacktoberfest, I think we can use that to our advantage.

**Comment by harsh183** [comment]
@cristianoliveira Can we close this issue if you added all those links, people need not to visit old issues with many comments, maybe we can add a suggestions guide on the contribution page instead.

**Comment by cristianoliveira** [comment]
Sure!
