### ISSUE TITLE
Greece flag not being properly displayed

### ISSUE THREAD

**Issue by lidimayra** [cristianoliveira/awesome4girls#65]
### Occurrence 1: in [Conference Talks](https://github.com/cristianoliveira/awesome4girls/#conferencestalks) section
![greece01](https://user-images.githubusercontent.com/8002618/31209328-9d32feb6-a960-11e7-9680-d82aaaba725d.png)

---

### Occurence 2: in [Content](https://github.com/cristianoliveira/awesome4girls/#content) section
![greece02](https://user-images.githubusercontent.com/8002618/31209334-a223b564-a960-11e7-88d1-4cf71759a0dd.png)

**Comment by harsh183** [comment]
![image](https://user-images.githubusercontent.com/7780198/31209622-d371a36c-a9a9-11e7-97d2-c9b72115b898.png)
![image](https://user-images.githubusercontent.com/7780198/31209631-ea9c8af2-a9a9-11e7-9c3a-b53a8940a662.png)

This is what it looks on mine, being on Firefox. Let me have a look.

**Comment by harsh183** [comment]
Yup, looks like I'm seeing the alt text there.

**Comment by harsh183** [comment]
https://github.com/cristianoliveira/awesome4girls/pull/67

**Comment by harsh183** [comment]
@lidimayra Thanks for the report.

**Comment by lidimayra** [comment]
@harsh183 my pleasure! :smile_cat:
