### ISSUE TITLE
New item: Women Hack for Non-Profits - http://www.womenhackfornonprofits.com/

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#71]
http://www.womenhackfornonprofits.com/

1. Write description
2. Place under right category
3. Create commit with new entry in the README.md file
4. Open PR and link to this issue

**Comment by swentling87** [comment]
I'll do this too!

**Comment by harsh183** [comment]
I left a comment, once you deal with that I'll merge it :)
