### ISSUE TITLE
Ada Lovelace Day

### ISSUE THREAD

**Issue by lightwavefeesh** [cristianoliveira/awesome4girls#76]
Today is [Ada Lovelace Day](https://findingada.com/). It's an event held on the second Tuesday of October to celebrate women in STEM fields and their achievements, and encourage would-be STEM participants to pursue those fields.

Would this be worth adding to the list?

**Comment by harsh183** [comment]
I think it fits exactly what we are looking for. Write a description, add it to the README.md and submit a pull request and I'll check it out.
