### ISSUE TITLE
Feat: Add - The Girls in Tech Catalyst Conference

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#99]
Link: http://catalystsf.girlsintech.org/

What you have to do:

1. Write description
2. Place under right category
3. Create commit with new entry in the README.md file
4. Open PR and link to this issue

**Comment by EggplantPlanter** [comment]
Hi this is my first hacktober, can I take on this request?

**Comment by harsh183** [comment]
@EggplantPlanter You are most welcome to :+1: 

On a side note, make sure to finish 4 PRs by the end of this month otherwise you won't get a shirt.

Take a look at the existing list on how things are done, and let me know if you have any issues.
